IoT_Server/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from devices import urls
from accounts import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('devices/', include('devices.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.login, name='login'),
    ]

clients/urls.py
from django.urls import pathfrom . import views

app_name = 'clients'

urlpatterns = [
    path('toggle/', views.toggle, name='toggle'),
    path('turnon/', views.turnOn, name='turnon'),
    path('turnoff/', views.turnOff, name='turnoff')
    ]

devices/urls.py
from django.urls import path
from . import views

app_name = 'devices'

urlpatterns = [
    path('open/<int:deviceID>', views.open, name='open'),
    ]

accounts/models.py
from django.db import models

# Create your models here.

clients/models.py
from django.db import models

# Create your models here.
class RegisteredClients(models.Model):
    
    class Meta: # a class to fix plural name that shows in the admin site
        verbose_name_plural = 'Registered Clients'
    
    #id field is automatically added by django
    dateAdded = models.DateTimeField(auto_now_add=True)
    hostname = models.CharField(max_length=100, null=False)
    ipaddress = models.CharField(max_length=20, null=False)
    port = models.CharField(max_length=10, null=False, default='80')
    publickey = models.CharField(max_length=1000, null=False)
    # add type field
    # add nickname field
    
    def __str__(self):
        return self.hostname + ' - ' + self.ipaddress + ':' + self.port

devices/models.py
from django.db import models
from django.core.validators import RegexValidator

# Create your models here.
class Devices(models.Model):
    '''
    A model table that holds information for connected relays, sensors, etc.
    '''
    class Meta: # a class to fix plural name that shows in the admin site
        verbose_name_plural = 'Devices'
    
    # tuple for type choices
    typeChoices = (
        ('s', 'sensor'),
        ('r', 'relay'),
        )
    
    # -- id field automatically created by django
    name = models.CharField(max_length=50)
    display_name = models.CharField(max_length=2, unique=True)
    type = models.CharField(max_length=1, choices=typeChoices)
    lastTime = models.DateTimeField(null=True, default=None)
    pin = models.CharField(max_length=2, unique=True, validators=[RegexValidator(r'^\d{1,10}$')])
    pinTime = models.CharField(max_length = 1, validators=[RegexValidator(r'^\d{1,10}$')])
        
    def __str__(self):
        return self.name + ' - ' + [element for element in self.typeChoices if element[0] == self.type][0][1]

IoT_Server/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required
from devices.models import Devices
import datetime
import pytz

# Create your views here.
@login_required(login_url='accounts:login')
def index(request):
    devices = Devices.objects.all()
    
    # used to make today and yesterday datetime objects offset-aware in order
    # to compare them with lastTime of device inside html template
    
    utc = pytz.UTC
    
    today = datetime.datetime.now().replace(hour=0, minute=0,
                                            second=0, microsecond=0)
    today = utc.localize(today)
    yesterday = today - datetime.timedelta(days=1)
    
    
    return render(request, 'index.html', {'devices': devices, 'today': today, 'yesterday': yesterday})

accounts/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request, 'accounts/login.html')

clients/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from clients.zeroconf.registerZeroconfService import registerService, unregisterService

# Create your views here.
def toggle(request):
    return render(request, 'clients/toggleAvahi.html')
    
def turnOn(request):
    print("turned on")
    registerService()
    return HttpResponse("ok")

def turnOff(request):
    print("turned off")
    unregisterService()
    return HttpResponse("ok")

devices/views.py
from django.shortcuts import render
from django.http.response import HttpResponse, HttpResponseNotFound
from .models import Devices
import time
import datetime

# Create your views here.
def open(request, deviceID):
    device = Devices.objects.get(id = deviceID)
    try:
        triggerRelay(device.pin, device.pinTime)
        updateLastTime(device)
    except:
        return HttpResponseNotFound()
    
    return HttpResponse()

def triggerRelay(pin, timeout):
    pin = int(pin)
    timeout = int(timeout)
    
    gpio.setup(pin, gpio.OUT)
    gpio.output(pin, gpio.HIGH)
    
    print("Triggering pin " + str(pin) + " for " + timeout + " seconds...")
    
    time.sleep(timeout)
    gpio.output(pin, gpio.LOW)
    print("done.")
    
def updateLastTime(device):
    device.lastTime = datetime.datetime.now()
    device.save()

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block title %}Home Access Controller{% endblock %}

{% block main-content %}

	<div class="col-12">
		<p class="mainLabel">You are not logged in.</p>
	</div>
	
{% endblock %}

clients/templates/clients/toggleAvahi.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Toggle Avahi Discovery</title>
  </head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>
    $(document).ready(function(){
      $("#on").click(function(){
        $.get("{% url 'clients:turnon' %}");
        console.log("on");
      })
    });

    $(document).ready(function(){
      $("#off").click(function(){
        $.get("{% url 'clients:turnoff' %}");
        console.log("off");
      })
    });
  </script>

  <style>
    div#on {
      background-color: #47a434;
      width: 50px;
      height: 50px;
    }

    div#off {
      background-color: #ad2c24;
      width: 50px;
      height: 50px;
    }
  </style>

  <body>
    <div id="on"></div>
    <div id="off"></div>
  </body>
</html>

devices/templates/devices/toggleAvahi.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Toggle Avahi Discovery</title>
  </head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>
    $(document).ready(function(){
      $("#on").click(function(){
        $.get("{% url 'devices:turnon' %}");
        console.log("on");
      })
    });

    $(document).ready(function(){
      $("#off").click(function(){
        $.get("{% url 'devices:turnoff' %}");
        console.log("off");
      })
    });
  </script>

  <style>
    div#on {
      background-color: #47a434;
      width: 50px;
      height: 50px;
    }

    div#off {
      background-color: #ad2c24;
      width: 50px;
      height: 50px;
    }
  </style>

  <body>
    <div id="on"></div>
    <div id="off"></div>
  </body>
</html>

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap dependencies -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>    <!-- End Bootstrap dependencies -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!-- custom styling -->
    <!-- Bootstrap dependencies -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>

  </head>
  <body>
    <header id="navbar" class="navbar navbar-expand-md navbar-dark bg-dark mb-5">
      <div class="container-fluid">
        <a class="navbar-brand pt-0" href="{% url 'home' %}">Home Controller</a>
        <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse w-100" id="collapsingNavbar">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link text-important" href="#">Doors</a></li>
            <li class="nav-item"><a class="nav-link text-important" href="#">Sensors</a></li>
          </ul>
        </div> -->
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><button type="button" class="btn btn-info" onclick="">Login</button></li>
        </ul>
      </div>
    </header>

    <div class="container">
      <div class="row small-gutters">
        {% block main-content %}
        {% endblock %}
      </div>
    </div>

    <div id="successAlert" class="alert alert-success collapse">
      <strong>Success:</strong> Door opened.
    </div>
    
    <div id="failedAlert" class="alert alert-danger collapse">
      <strong>Failed:</strong> Door couldn't be opened.
    </div>

  </body>
</html>

templates/index.html
{% extends 'base_layout.html' %}

{% block title %}Home Access Controller{% endblock %}

{% block main-content %}

	{% if devices.count == 0 %}
		<div class="col-12">
			<p class="mainLabel">You haven't setup any device yet.</p>
		</div>
	{% else %}
		{% for device in devices %}
		<article class="col-6 col-md-4 col-xl-3">
          <div class="square">
            <div class="fullcontent">
              <div class="row w-75 h-100 mx-auto">
                <div class="col-sm-12 h-75 p-3">
                  <div id="device1" class="circlebtn" onclick="openDoor('{{ device.id }}', '{{ device.name }}')">
                    <div class="row align-items-center h-100">
                      <div class="activityNumber my-auto">{{ device.display_name }}</div>
                    </div>
                  </div>
                </div>
                <div class="deviceActivityContainer col-sm-12 h-25">
                  <div class="deviceActivity">
                    <span class="activityLabel">Last Opened </span>
                    <span class="activityTime">
                    	{% if device.lastTime == None %}
                    		Never Opened
                    	{% else %}
                    	
                    		{% if device.lastTime >= today %}
                    			Today
	                    		<strong>{{ device.lastTime|date:'h:i A'  }}</strong>
	                    	{% elif device.lastTime >= yesterday %}
	                    		Yesterday
	                    		<strong>{{ device.lastTime|date:'h:i A'  }}</strong>
                    		{% else %}
	                    		{{ device.lastTime|date:'M d, Y '  }}
	                    		<strong>{{ device.lastTime|date:'h:i A'  }}</strong>
                    		{% endif %}
                    		
                    	{% endif %}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </article>
	{% endfor %}
	{% endif %}
{% endblock %}